CREATE TABLE "bilans" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "bilans_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_evt_journal_reqs" integer NOT NULL,
	"date_creation" timestamp with time zone DEFAULT now() NOT NULL,
	"date_maj" timestamp with time zone DEFAULT now() NOT NULL,
	"siret" text NOT NULL,
	"nom" text NOT NULL,
	"debut_exercice" date NOT NULL,
	"fin_exercice" date NOT NULL,
	"version" integer NOT NULL,
	"date_bilan" date NOT NULL,
	"stck_vol_h_nais_mi" double precision,
	"stck_val_h_nais_mi" numeric(15, 2),
	"stck_vol_h_nais_kg" double precision,
	"stck_val_h_nais_kg" numeric(15, 2),
	"stck_vol_hd_elv" double precision,
	"stck_val_hd_elv" numeric(15, 2),
	"stck_vol_h_elv" double precision,
	"stck_val_h_elv" numeric(15, 2),
	"stck_vol_h_conso" double precision,
	"stck_val_h_conso" numeric(15, 2),
	"stck_vol_m_naiss" double precision,
	"stck_val_m_naiss" numeric(15, 2),
	"stck_vol_md_elv" double precision,
	"stck_val_md_elv" numeric(15, 2),
	"stck_vol_m_conso" double precision,
	"stck_val_m_conso" numeric(15, 2),
	"stck_vol_p_naiss" double precision,
	"stck_val_p_naiss" numeric(15, 2),
	"stck_vol_pd_elv" double precision,
	"stck_val_pd_elv" numeric(15, 2),
	"stck_vol_p_conso" double precision,
	"stck_val_p_conso" numeric(15, 2),
	"stck_vol_g_larv" double precision,
	"stck_val_g_larv" numeric(15, 2),
	"stck_vol_g_preg" double precision,
	"stck_val_g_preg" numeric(15, 2),
	"stck_vol_g_conso" double precision,
	"stck_val_g_conso" numeric(15, 2),
	"lib_pois" text,
	"stck_vol_pois" double precision,
	"stck_val_pois" numeric(15, 2),
	"lib_a_coq" text,
	"stck_vol_a_coq" double precision,
	"stck_val_a_coq" numeric(15, 2),
	"lib_ap_aqua" text,
	"stck_vol_ap_aqua" double precision,
	"stck_val_ap_aqua" numeric(15, 2),
	"vol_vt_h_naiss_fr" double precision,
	"vol_vt_hd_elv_ue" double precision,
	"cahd_elv_ue" numeric(15, 2),
	"vol_vt_hd_elv_au" double precision,
	"cahd_elv_au" numeric(15, 2),
	"vol_vt_h_elv_fr" double precision,
	"cah_elv_fr" numeric(15, 2),
	"vol_vt_h_elv_ue" double precision,
	"cah_elv_ue" numeric(15, 2),
	"vol_vt_h_elv_au" double precision,
	"cah_elv_au" numeric(15, 2),
	"vol_vt_h_co_fr_pro" double precision,
	"cah_co_fr_pro" numeric(15, 2),
	"vol_vt_h_co_fr_det" double precision,
	"cah_co_fr_det" numeric(15, 2),
	"vol_vt_h_co_fr_gros" double precision,
	"cah_co_fr_gros" numeric(15, 2),
	"vol_vt_h_co_fr_pce" double precision,
	"cah_co_fr_pce" numeric(15, 2),
	"vol_vt_h_co_fr_pgms" double precision,
	"cah_co_fr_pgms" numeric(15, 2),
	"vol_vt_h_co_fr_deg" double precision,
	"cah_co_fr_deg" numeric(15, 2),
	"vol_vt_h_co_ue_pro" double precision,
	"cah_co_ue_pro" numeric(15, 2),
	"vol_vt_h_co_ue_gros" double precision,
	"cah_co_ue_gros" numeric(15, 2),
	"vol_vt_h_co_au_pro" double precision,
	"cah_co_au_pro" numeric(15, 2),
	"vol_vt_h_co_au_gros" double precision,
	"cah_co_au_gros" numeric(15, 2),
	"vol_vt_h_fr_n_cat" double precision,
	"cah_fr_n_cat" numeric(15, 2),
	"vol_vt_m_naiss_fr" double precision,
	"cam_naiss_fr" numeric(15, 2),
	"vol_vt_m_naiss_ue" double precision,
	"cam_naiss_ue" numeric(15, 2),
	"vol_vt_m_naiss_au" double precision,
	"cam_naiss_au" numeric(15, 2),
	"vol_vt_md_elv_fr" double precision,
	"camd_elv_fr" numeric(15, 2),
	"vol_vt_md_elv_ue" double precision,
	"camd_elv_ue" numeric(15, 2),
	"vol_vt_md_elv_au" double precision,
	"camd_elv_au" numeric(15, 2),
	"vol_vt_m_co_fr_pro" double precision,
	"cam_co_fr_pro" numeric(15, 2),
	"vol_vt_m_co_fr_det" double precision,
	"cam_co_fr_det" numeric(15, 2),
	"vol_vt_m_co_fr_gros" double precision,
	"cam_co_fr_gros" numeric(15, 2),
	"vol_vt_m_co_fr_pce" double precision,
	"cam_co_fr_pce" numeric(15, 2),
	"vol_vt_m_co_fr_pgms" double precision,
	"cam_co_fr_pgms" numeric(15, 2),
	"vol_vt_m_co_fr_deg" double precision,
	"cam_co_fr_deg" numeric(15, 2),
	"vol_vt_m_co_ue_pro" double precision,
	"cam_co_ue_pro" numeric(15, 2),
	"vol_vt_m_co_ue_gros" double precision,
	"cam_co_ue_gros" numeric(15, 2),
	"vol_vt_m_co_au_pro" double precision,
	"cam_co_au_pro" numeric(15, 2),
	"vol_vt_m_co_au_gros" double precision,
	"cam_co_au_gros" numeric(15, 2),
	"vol_vt_m_fr_n_cat" double precision,
	"cam_fr_n_cat" numeric(15, 2),
	"vol_vt_p_naiss_fr" double precision,
	"cap_naiss_fr" numeric(15, 2),
	"vol_vt_p_naiss_ue" double precision,
	"cap_naiss_ue" numeric(15, 2),
	"vol_vt_p_naiss_au" double precision,
	"cap_naiss_au" numeric(15, 2),
	"vol_vt_pd_elv_fr" double precision,
	"capd_elv_fr" numeric(15, 2),
	"vol_vt_pd_elv_ue" double precision,
	"capd_elv_ue" numeric(15, 2),
	"vol_vt_pd_elv_au" double precision,
	"capd_elv_au" numeric(15, 2),
	"vol_vt_p_co_fr_pro" double precision,
	"cap_co_fr_pro" numeric(15, 2),
	"vol_vt_p_co_fr_det" double precision,
	"cap_co_fr_det" numeric(15, 2),
	"vol_vt_p_co_fr_gros" double precision,
	"cap_co_fr_gros" numeric(15, 2),
	"vol_vt_p_co_fr_pce" double precision,
	"cap_co_fr_pce" numeric(15, 2),
	"vol_vt_p_co_fr_pgms" double precision,
	"cap_co_fr_pgms" numeric(15, 2),
	"vol_vt_p_co_fr_deg" double precision,
	"cap_co_fr_deg" numeric(15, 2),
	"vol_vt_p_co_ue_pro" double precision,
	"cap_co_ue_pro" numeric(15, 2),
	"vol_vt_p_co_ue_gros" double precision,
	"cap_co_ue_gros" numeric(15, 2),
	"vol_vt_p_co_au_pro" double precision,
	"cap_co_au_pro" numeric(15, 2),
	"vol_vt_p_co_au_gros" double precision,
	"cap_co_au_gros" numeric(15, 2),
	"vol_vt_p_fr_n_cat" double precision,
	"cap_fr_n_cat" numeric(15, 2),
	"vol_vt_g_naiss_fr" double precision,
	"cag_naiss_fr" numeric(15, 2),
	"vol_vt_g_naiss_ue" double precision,
	"cag_naiss_ue" numeric(15, 2),
	"vol_vt_g_naiss_au" double precision,
	"cag_naiss_au" numeric(15, 2),
	"vol_vt_gd_elv_fr" double precision,
	"cagd_elv_fr" numeric(15, 2),
	"vol_vt_gd_elv_ue" double precision,
	"cagd_elv_ue" numeric(15, 2),
	"vol_vt_gd_elv_au" double precision,
	"cagd_elv_au" numeric(15, 2),
	"vol_vt_g_co_fr_pro" double precision,
	"cag_co_fr_pro" numeric(15, 2),
	"vol_vt_g_co_fr_det" double precision,
	"cag_co_fr_det" numeric(15, 2),
	"vol_vt_g_co_fr_gros" double precision,
	"cag_co_fr_gros" numeric(15, 2),
	"vol_vt_g_co_fr_pce" double precision,
	"cag_co_fr_pce" numeric(15, 2),
	"vol_vt_g_co_fr_pgms" double precision,
	"cag_co_fr_pgms" numeric(15, 2),
	"vol_vt_g_co_fr_deg" double precision,
	"cag_co_fr_deg" numeric(15, 2),
	"vol_vt_g_co_ue_pro" double precision,
	"cag_co_ue_pro" numeric(15, 2),
	"vol_vt_g_co_ue_gros" double precision,
	"cag_co_ue_gros" numeric(15, 2),
	"vol_vt_g_co_au_pro" double precision,
	"cag_co_au_pro" numeric(15, 2),
	"vol_vt_g_co_au_gros" double precision,
	"cag_co_au_gros" numeric(15, 2),
	"vol_vt_g_fr_n_cat" double precision,
	"cag_fr_n_cat" numeric(15, 2),
	"vol_vt_pois_fr" double precision,
	"ca_pois_fr" numeric(15, 2),
	"vol_vt_a_coq_fr" double precision,
	"caa_coq_fr" numeric(15, 2),
	"vol_vt_a_coq_ue" double precision,
	"caa_coq_ue" numeric(15, 2),
	"vol_vt_a_coq_au" double precision,
	"caa_coq_au" numeric(15, 2),
	"vol_vt_ap_aqua_fr" double precision,
	"caap_aqua_fr" numeric(15, 2),
	"vol_vt_ap_aqua_ue" double precision,
	"caap_aqua_ue" numeric(15, 2),
	"vol_vt_ap_aqua_au" double precision,
	"caap_aqua_au" numeric(15, 2),
	"pct_cah_naiss_fr" double precision,
	"pct_cah_naiss_ue" double precision,
	"pct_cah_naiss_au" double precision,
	"pct_cahd_elv_fr" double precision,
	"pct_cahd_elv_ue" double precision,
	"pct_cahd_elv_au" double precision,
	"pct_cah_elv_fr" double precision,
	"pct_cah_elv_ue" double precision,
	"pct_cah_elv_au" double precision,
	"pct_cah_co_fr_pro" double precision,
	"pct_cah_co_fr_det" double precision,
	"pct_cah_co_fr_gros" double precision,
	"pct_cah_co_fr_pce" double precision,
	"pct_cah_co_fr_pgms" double precision,
	"pct_cah_co_fr_deg" double precision,
	"pct_cah_co_ue_pro" double precision,
	"pct_cah_co_ue_gros" double precision,
	"pct_cah_co_au_pro" double precision,
	"pct_cah_co_au_gros" double precision,
	"pct_cam_naiss_fr" double precision,
	"pct_cam_naiss_ue" double precision,
	"pct_cam_naiss_au" double precision,
	"pct_camd_elv_fr" double precision,
	"pct_camd_elv_ue" double precision,
	"pct_camd_elv_au" double precision,
	"pct_cam_co_fr_pro" double precision,
	"pct_cam_co_fr_det" double precision,
	"pct_cam_co_fr_gros" double precision,
	"pct_cam_co_fr_pce" double precision,
	"pct_cam_co_fr_pgms" double precision,
	"pct_cam_co_fr_deg" double precision,
	"pct_cam_co_ue_pro" double precision,
	"pct_cam_co_ue_gros" double precision,
	"pct_cam_co_au_pro" double precision,
	"pct_cam_co_au_gros" double precision,
	"pct_cap_naiss_fr" double precision,
	"pct_cap_naiss_ue" double precision,
	"pct_cap_naiss_au" double precision,
	"pct_capd_elv_fr" double precision,
	"pct_capd_elv_ue" double precision,
	"pct_capd_elv_au" double precision,
	"pct_cap_co_fr_pro" double precision,
	"pct_cap_co_fr_det" double precision,
	"pct_cap_co_fr_gros" double precision,
	"pct_cap_co_fr_pce" double precision,
	"pct_cap_co_fr_pgms" double precision,
	"pct_cap_co_fr_deg" double precision,
	"pct_cap_co_ue_pro" double precision,
	"pct_cap_co_ue_gros" double precision,
	"pct_cap_co_au_pro" double precision,
	"pct_cap_co_au_gros" double precision,
	"pct_cag_naiss_fr" double precision,
	"pct_cag_naiss_ue" double precision,
	"pct_cag_naiss_au" double precision,
	"pct_cagd_elv_fr" double precision,
	"pct_cagd_elv_ue" double precision,
	"pct_cagd_elv_au" double precision,
	"pct_cag_co_fr_pro" double precision,
	"pct_cag_co_fr_det" double precision,
	"pct_cag_co_fr_gros" double precision,
	"pct_cag_co_fr_pce" double precision,
	"pct_cag_co_fr_pgms" double precision,
	"pct_cag_co_fr_deg" double precision,
	"pct_cag_co_ue_pro" double precision,
	"pct_cag_co_ue_gros" double precision,
	"pct_cag_co_au_pro" double precision,
	"pct_cag_co_au_gros" double precision,
	"pct_ca_pois_fr" double precision,
	"pct_caa_coq_fr" double precision,
	"pct_caa_coq_ue" double precision,
	"pct_caa_coq_au" double precision,
	"pct_caap_aqua_fr" double precision,
	"pct_caap_aqua_ue" double precision,
	"pct_caap_aqua_au" double precision,
	"ca_tot" numeric(15, 2),
	"ca_ach_rev" numeric(15, 2),
	"arev_d" numeric(15, 2),
	"subv" numeric(15, 2),
	"sub_invest" numeric(15, 2),
	"salaire" numeric(15, 2),
	"mo_ext" numeric(15, 2),
	"ch_soc_non_sal" numeric(15, 2),
	"non_sal" numeric(15, 2),
	"energie" numeric(15, 2),
	"ach_h_naiss" numeric(15, 2),
	"vol_ach_h_naiss" double precision,
	"ach_hd_elv" numeric(15, 2),
	"vol_ach_hd_elv" double precision,
	"ach_h_elv" numeric(15, 2),
	"vol_ach_h_elv" double precision,
	"ach_h_conso" numeric(15, 2),
	"vol_ach_h_conso" double precision,
	"ach_m_naiss" numeric(15, 2),
	"vol_ach_mnaiss" double precision,
	"ach_md_elv" numeric(15, 2),
	"vol_ach_md_elv" double precision,
	"ach_m_conso" numeric(15, 2),
	"vol_ach_m_conso" double precision,
	"ach_p_naiss" numeric(15, 2),
	"vol_ach_pnaiss" double precision,
	"ach_pd_elv" numeric(15, 2),
	"vol_ach_pd_elv" double precision,
	"ach_p_conso" numeric(15, 2),
	"vol_ach_p_conso" double precision,
	"ach_g_naiss" numeric(15, 2),
	"vol_ach_gnaiss" double precision,
	"ach_gd_elv" numeric(15, 2),
	"vol_ach_gd_elv" double precision,
	"ach_g_conso" numeric(15, 2),
	"vol_ach_g_conso" double precision,
	"ach_acoq" numeric(15, 2),
	"vol_ach_acoq" double precision,
	"ach_ap_aqua" numeric(15, 2),
	"vol_ach_ap_aqua" double precision,
	"ct_alim" numeric(15, 2),
	"ct_op" numeric(15, 2),
	"repar" numeric(15, 2),
	"amort" numeric(15, 2),
	"ct_fi" numeric(15, 2),
	"prod_fi" numeric(15, 2),
	"capito" numeric(15, 2),
	"ct_excp" numeric(15, 2),
	"prod_excp" numeric(15, 2),
	"actif" numeric(15, 2),
	"invest" numeric(15, 2),
	"acqui_immo" numeric(15, 2),
	"cess_immo" numeric(15, 2),
	"dettes" numeric(15, 2),
	"emprunts" numeric(15, 2),
	"ca_compt" numeric(15, 2),
	"tot_prod" numeric(15, 2),
	"tot_charge" numeric(15, 2),
	"va" numeric(15, 2),
	"ebe" numeric(15, 2),
	"resultat_courant" numeric(15, 2),
	"resultat_net" numeric(15, 2),
	CONSTRAINT "siret_check" CHECK ("bilans"."siret" ~ '^\d{14}$')
);

CREATE TABLE "dirigeant_es" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "dirigeant_es_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_bilan" integer NOT NULL,
	"nom" text NOT NULL,
	"prenom" text NOT NULL,
	"annee_naissance" smallint,
	"genre" text,
	"annee_entree" smallint,
	"diplome" text,
	"diplome_aquacole" text,
	"regime_social" text,
	"taux_travail" integer
);

CREATE TABLE "journal_requetes" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "journal_requetes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_jeton" integer NOT NULL,
	"date_creation" timestamp with time zone DEFAULT now() NOT NULL,
	"version_api" integer NOT NULL,
	"pathname" text NOT NULL,
	"href" text NOT NULL,
	"methode" text NOT NULL,
	"data" json NOT NULL,
	"status" integer
);

CREATE TABLE "jetons_api" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "jetons_api_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"date_creation" timestamp with time zone DEFAULT now() NOT NULL,
	"hachage" text NOT NULL,
	"valide" boolean DEFAULT true NOT NULL,
	"nom_partenaire" text NOT NULL,
	"siret_partenaire" text NOT NULL,
	"courriel_partenaire" text NOT NULL,
	CONSTRAINT "jetons_api_hachage_unique" UNIQUE("hachage"),
	CONSTRAINT "siret_check" CHECK ("jetons_api"."siret_partenaire" ~ '^\d{14}$')
);

CREATE TABLE "sessions" (
	"id" text PRIMARY KEY NOT NULL,
	"id_utilisateur" integer NOT NULL,
	"date_creation" timestamp with time zone DEFAULT now() NOT NULL,
	"date_expiration" timestamp with time zone NOT NULL
);

CREATE TABLE "utilisateurs" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "utilisateurs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"date_creation" timestamp with time zone DEFAULT now() NOT NULL,
	"date_maj" timestamp with time zone DEFAULT now() NOT NULL,
	"courriel" text
);

ALTER TABLE "bilans" ADD CONSTRAINT "bilans_id_evt_journal_reqs_journal_requetes_id_fk" FOREIGN KEY ("id_evt_journal_reqs") REFERENCES "public"."journal_requetes"("id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "dirigeant_es" ADD CONSTRAINT "dirigeant_es_id_bilan_bilans_id_fk" FOREIGN KEY ("id_bilan") REFERENCES "public"."bilans"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "journal_requetes" ADD CONSTRAINT "journal_requetes_id_jeton_jetons_api_id_fk" FOREIGN KEY ("id_jeton") REFERENCES "public"."jetons_api"("id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_id_utilisateur_utilisateurs_id_fk" FOREIGN KEY ("id_utilisateur") REFERENCES "public"."utilisateurs"("id") ON DELETE cascade ON UPDATE no action;